name: 'Daily Job'

on:
  schedule:
    - cron: '0 16 * * *' # UTC时间每天16:00运行（北京时间00:00）
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 关键：获取完整历史记录

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencc-python-reimplemented

      - name: Run Python script
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add live.txt live.m3u live_lite.txt live_lite.m3u others.txt
          git commit -m ":tada: AutoUpdate $(date +'%Y%m%d %H:%M')"

      - name: Force push changes
        run: |
          git push --force origin HEAD:main
